key: BOSCH_B2B
name: BOSCH B2B
plp:
  show.bazaar.voice: true
  show.no.results: false
 pdp:
  details.tabs.visible: Tech_Specs,Reviews
  
 
key: SIEMENS_B2B
name: SIEMENS B2B
plp:
  show.bazaar.voice: false
  show.no.results: false
 pdp:
  details.tabs.visible: Reviews
