testConfig:
 - key: BOSCH_B2B
   name: BOSCH B2B
   bazaarvoice: true
   noresults: false
   tabsvisible:
    - Tech_Specs
    - Reviews
 - key: SIEMENS_B2B
   name: SIEMENS B2B
   bazaarvoice: true
   noresults: false
   tabsvisible:
    - Tech_Specs
    - Promotion

