{
  "type": "object",
  "properties": {
    "testConfig": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "key": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "plp": {
              "type": "object",
              "properties": {
                "show.bazaar.voice": {
                  "type": "boolean"
                },
                "show.no.results": {
                  "type": "boolean"
                }
              },
              "required": [
                "show.bazaar.voice",
                "show.no.results"
              ]
            },
            "pdp": {
              "type": "object",
              "properties": {
                "details.tabs.visible": {
                  "type": "array",
                  "items": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    }
                  ]
                }
              },
              "required": [
                "details.tabs.visible"
              ]
            }
          },
          "required": [
            "key",
            "name",
            "plp",
            "pdp"
          ]
        },
        {
          "type": "object",
          "properties": {
            "key": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "plp": {
              "type": "object",
              "properties": {
                "show.bazaar.voice": {
                  "type": "boolean"
                },
                "show.no.results": {
                  "type": "boolean"
                }
              },
              "required": [
                "show.bazaar.voice",
                "show.no.results"
              ]
            },
            "pdp": {
              "type": "object",
              "properties": {
                "details.tabs.visible": {
                  "type": "array",
                  "items": [
                    {
                      "type": "string"
                    }
                  ]
                }
              },
              "required": [
                "details.tabs.visible"
              ]
            }
          },
          "required": [
            "key",
            "name",
            "plp",
            "pdp"
          ]
        },
        {
          "type": "object",
          "properties": {
            "key": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "plp": {
              "type": "object",
              "properties": {
                "show.bazaar.voice": {
                  "type": "boolean"
                },
                "show.no.results": {
                  "type": "boolean"
                }
              },
              "required": [
                "show.bazaar.voice",
                "show.no.results"
              ]
            },
            "pdp": {
              "type": "object",
              "properties": {
                "details.tabs.visible": {
                  "type": "array",
                  "items": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "string"
                    }
                  ]
                }
              },
              "required": [
                "details.tabs.visible"
              ]
            }
          },
          "required": [
            "key",
            "name",
            "plp",
            "pdp"
          ]
        }
      ]
    }
  },
  "required": [
    "testConfig" 
  ]
}
