type: object
properties:
  $schema:
    type: string
  type:
    type: string
  items:
    type: object
    properties:
      $ref:
        type: string
  definitions:
    type: object
    properties:
      Welcome8Element:
        type: object
        properties:
          type:
            type: string
          additionalProperties:
            type: boolean
          properties:
            type: object
            properties:
              key:
                type: object
                properties:
                  type:
                    type: string
              name:
                type: object
                properties:
                  type:
                    type: string
              plp:
                type: object
                properties:
                  type:
                    type: string
                  additionalProperties:
                    type: object
                    properties:
                      type:
                        type: string
              pdp:
                type: object
                properties:
                  $ref:
                    type: string
          required:
            type: array
            items:
              type: string
          title:
            type: string
      PDP:
        type: object
        properties:
          type:
            type: string
          additionalProperties:
            type: boolean
          properties:
            type: object
            properties:
              details.tabs.visible:
                type: object
                properties:
                  type:
                    type: string
                  items:
                    type: object
                    properties:
                      type:
                        type: string
          required:
            type: array
            items:
              type: string
          title:
            type: string
