type: object
properties:
  $schema:
    type: string
  type:
    type: string
  items:
    type: object
    properties:
      $ref:
        type: string
  definitions:
    type: object
    properties:
      Welcome6Element:
        type: object
        properties:
          type:
            type: string
          additionalProperties:
            type: boolean
          properties:
            type: object
            properties:
              key:
                type: object
                properties:
                  type:
                    type: string
              name:
                type: object
                properties:
                  type:
                    type: string
              plp.show.bazaar.voice:
                type: object
                properties:
                  type:
                    type: string
              plp.show.no.results:
                type: object
                properties:
                  type:
                    type: string
              pdp.details.tabs.visible:
                type: object
                properties:
                  type:
                    type: string
                  items:
                    type: object
                    properties:
                      type:
                        type: string
          required:
            type: array
            items:
              type: string
          title:
            type: string
