testConfig:
  - key: 
      type: string
      required: true
    name: 
      type: string
      required: true
    bazaarvoice:
      type: boolean
      required: true
    noresults: 
      type: boolean
      required: true
    tabsvisible: 
        - type: string
    
      
