testConfig:
  - key: 
      type: string
      required: true
    name: 
      type: string
      required: true
    plp.show.bazaar.voice:: 
      type: boolean
      required: true
    plp.show.no.results: 
      type: boolean
      required: true
    pdp.details.tabs.visible: 
      type: array
      required: true
    
      
