testConfig:
 - key: BOSCH_B2B
   name: BOSCH B2B
   plp_bazaarvoice: true
   plp_noresults: false
   pdp_tabsvisible:
    - Tech_Specs
    - Reviews
 - key: SIEMENS_B2B
   name: SIEMENS B2B
   plp_bazaarvoice: true
   plp_noresults: false
   pdp_tabsvisible:
    - Tech_Specs
    - Promotion
 - key: SIEMENS_B2C
   name: SIEMENS B2B
   plp_bazaarvoice: true
   plp_noresults: false
   pdp_tabsvisible:
    - Tech_Specs
    
 - key: SIEMENS_B2B_2
   name: SIEMENS B2B
   plp_bazaarvoice: false
   pdp_tabsvisible:
    - Tech_Specs
