# This is a basic workflow to help you get started with Actions

name: Yaml Validation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  yaml-schema-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: JKarwatka/validate-yaml-schema-action@0.2.4-alpha

      with:
        files-to-validate: '[{ "path": "configfiles/Portugal_Config.yml", "schema": "schemas/schema.yml"},{ "path": "configfiles/Germany_Config.yml", "schema": "schemas/schema.yml"}]'

  
  # Uncomment to disable strict checks
        # no-strict: true
 

